// Break
export const INCREMENT_BREAK = "INCREMENT_BREAK";
export const DECREMENT_BREAK = "DECREMENT_BREAK";

// Session
export const INCREMENT_SESSION = "INCREMENT_SESSION";
export const DECREMENT_SESSION = "DECREMENT_SESSION";

// Timer Label
export const SESSION_END = "SESSION_END";
export const SESSION_START = "SESSION_START";
